### PR TITLE
feat: Add sea theme

### PR DESCRIPTION
**Pull request by AndreyKozhev**
## Description

Added new sea theme.

### Type of change

- [x] Updated documentation (updated the readme, templates, or other repo files)

## How Has This Been Tested?

- [ ] Tested locally with a valid username
- [ ] Tested locally with an invalid username
- [ ] Ran tests with `composer test`
- [ ] Added or updated test cases to test new features

## Checklist:

- [x] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [x] The code is properly formatted and is consistent with the existing code style
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots

image

### CODE REVIEW

**Comment by DenverCoder1** [comment]
Looks good, have you considered maybe making it less vibrant?

I'm thinking something less like primary blue such as `#1565C0` would be look better.

image

Of course it is up to you, though. Let me know what you think.

**Comment by AndreyKozhev** [comment]
Okay.

**Comment by AndreyKozhev** [comment]
Ready.

**Comment by AndreyKozhev** [comment]
I don't know why, but after I updated the branch to `DenverCoder1/github-readme-streak-stats:main`, the Prettier task failed in both pull requests.

**Comment by DenverCoder1** [comment]
Thanks!

Don't worry about the prettier stuff, was reworking some of it and it's not easy to make it work on PRs from forks, should be better now.

**Review by DenverCoder1 — APPROVED** [review]

**Comment by AndreyKozhev** [comment]
Okay.

**Pull request merged**
