### PR TITLE
feat: Adds navy-gear theme

### PR DESCRIPTION
**Pull request by amifth**
## Description

Added themes is name "navy-gear" and fixed

### CODE REVIEW

**Review by DenverCoder1 — APPROVED** [review]
Looks great! Thanks for the contribution :tada:

**Comment by DenverCoder1** [comment]
Would you be able to also update the list of themes in the docs?

See https://github.com/amifth/github-readme-streak-stats/blob/main/docs/themes/README.md

Just need to add this image

image

https://user-images.githubusercontent.com/20955511/153954354-60438cfa-d0a0-4737-936c-65b61faf637d.png

**Comment by amifth** [comment]
Ok, I will also update the theme list in the docs

**Review by amifth — COMMENTED** [review]
Update theme docs list on Readme.md

**Review by DenverCoder1 — APPROVED** [review]
Thanks!

**Pull request merged**
