### PR TITLE
feat: Add yellowdark theme

### PR DESCRIPTION
**Pull request by AndreyKozhev**
## Description

Added new yellowdark theme.

### Type of change

- [x] Updated documentation (updated the readme, templates, or other repo files)

## How Has This Been Tested?

- [x] Tested locally with a valid username
- [x] Tested locally with an invalid username
- [x] Ran tests with `composer test`
- [x] Added or updated test cases to test new features

## Checklist:

- [x] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [x] The code is properly formatted and is consistent with the existing code style
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### With border
image
### Without border
image

This are a screenshots from the demo site.

### CODE REVIEW

**Comment by DenverCoder1** [comment]
I find this pallete to be a bit similar to [`javascript-dark`](https://user-images.githubusercontent.com/20955511/180083504-357d51a7-ce86-4c34-a29d-b2aafe559d47.png) and [`great-gatsby`](https://user-images.githubusercontent.com/20955511/180083438-3529615b-ec70-439e-92e4-07a94ca0f607.png) but I feel the primary red seems to stand out a lot.

Maybe a shade of orange for the fire could be better, or possibly a duller red or matching yellow?

Feel free to let me know what you think. :+1: 

Additionally, the image for the docs can be obtained by doing a right-click on the picture on the demo site and copy in order to avoid having the extra white-space around the border.

**Comment by AndreyKozhev** [comment]
Perhaps. I'll try to change the color of the fire.

Thanks for the advice!

**Comment by AndreyKozhev** [comment]
How about this?

image

**Comment by DenverCoder1** [comment]
Looks good :+1:

**Comment by AndreyKozhev** [comment]
Okay.

**Comment by AndreyKozhev** [comment]
I have updated the code and docs.

**Review by DenverCoder1 — APPROVED** [review]
Thanks for the contribution :tada:

**Pull request merged**
