### PR TITLE
Deuteranopia friendly theme

### LINKED ISSUE #32: 🎨 Add more themes
If you have a creative theme you've designed that you think others may like to use, feel free to add it to the code!

### Requesting a theme

1. Open an issue describing your new theme in detail and optionally show an image.
2. Say in the issue if you would like someone else to add the theme.

### Designing a theme

1. Pick colors using the "advanced options" on the [Demo Site](https://github-readme-streak-stats.herokuapp.com/demo/).
2. Once you have chosen colors for all of the color properties, you will be able to add a theme.

### Adding a theme

1. Open an issue about your theme and optionally show an image
2. Say in the issue that you will be adding it yourself
3. Fork the repository and clone your fork to your computer
4. Create a new branch (you can name it with the name of your theme)
5. Edit [`themes.php`](https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/src/themes.php) to have your new theme colors by adding an array entry to the end. You can copy an existing entry for the correct formatting
6. Test your theme by running `composer start` and going to `http://localhost:8000/?user=<USERNAME>&theme=<THEME>` (you will need PHP installed to do this)
7. Add an entry to [`docs/themes/README.md`](https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/themes/README.md) with a **static** PNG image of your theme. (You can copy the image from the demo site when running locally - `http://localhost:8000/demo/?theme=<THEME>`)
8. Commit and push your changes to your fork
9. Open a pull request for merging your branch into this repo's main branch
10. Link the issue you created by typing `Closes #0` where #0 is the number of the issue you created. You can also do this through the "Linked issues" on the right-side panel after opening the Pull Request

Make sure to keep the spacing and formatting consistent.

Your theme will become available when your Pull Request is approved.

If you have any questions, feel free to ask!

### PR DESCRIPTION
**Pull request by tejas-nagchandi**
## Description

Added deuteranopia-friendly-theme.
This is inspired by [#357](https://github.com/github/roadmap/issues/357) of github roadmap.

**Intended Outcome**
Users with Deuteranopia color blindness can see more colors within their visible spectrum.

**Documentation**
I have also updated the theme README with a screenshot of how a person with Deuteranopia will see the stats. The screenshot is taken with the help of a [color blindness simulator](https://www.color-blindness.com/coblis-color-blindness-simulator)

References #32 

### Type of change

- [X] Bug fix (added a non-breaking change which fixes an issue)

## How Has This Been Tested?

- [X] Tested locally with a valid username
- [X] Tested locally with an invalid username
- [X] Ran tests with `composer test`

## Checklist:

- [X] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [X] The code is properly formatted and is consistent with the existing code style
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

## Screenshots

image

### CODE REVIEW

**Comment by tejas-nagchandi** [comment]
No clue why Prettier task failed, the same happened with #269
This time I even made sure that the spacing is fine.
Maybe some git attribute on my local is causing this issue.

**Comment by tejas-nagchandi** [comment]
@DenverCoder1 : It is because of the README update, I think it is better to have both views in the README, one with a regular user, and one with the "End User" (User with Deuteranopia)

**Comment by DenverCoder1** [comment]
> It is because of the README update

Yeah, the table column widths changed so Prettier is suggesting to increase the widths of the other rows as well. Don't worry about it.

**Comment by DenverCoder1** [comment]
Thanks for the contribution, the images seem to be a bit off-center and have some of the border cut off, you can avoid that by simply doing a right-click > copy image on the demo site and pasting it here.

I've gone ahead and tested it out so here are some images that can be used. The second is generated from the same site you mentioned.

`https://user-images.githubusercontent.com/20955511/181619555-1e541bf7-9f49-47ef-8ef7-20d63e2cb712.png`

image

`https://user-images.githubusercontent.com/20955511/181620032-4f65c980-a48b-4270-bf56-a6747e00386a.png`

image

Thanks!

**Comment by DenverCoder1** [comment]
Looks great! Thanks 👍

**Review by DenverCoder1 — APPROVED** [review]

**Pull request merged**
