### PR TITLE
added new theme: youtube-dark

### PR DESCRIPTION
**Pull request by wamikabro**
added youtube-dark theme for youtubers.

issue number #637 

### Type of change
theme 

- [✅] New feature (added a non-breaking change which adds functionality)
- [✅] Updated documentation (updated the readme, templates, or other repo files)

- [✅] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [✅] The code is properly formatted and is consistent with the existing code style
- [✅] I have made corresponding changes to the documentation
- [✅] My changes generate no new warnings

## Screenshots
youtube-dark

### CODE REVIEW

**Comment by DenverCoder1** [comment]
Looks good 👍

It seems that there are some extra files on the branch that were added and not needed, would you be able to remove those?

**Comment by wamikabro** [comment]
> Looks good 👍
> 
> It seems that there are some extra files on the branch that were added and not needed, would you be able to remove those?

Sure. Let me look for them and remove.

**Comment by wamikabro** [comment]
> Looks good 👍
> 
> It seems that there are some extra files on the branch that were added and not needed, would you be able to remove those?

Is it alright now? I removed all the files that I could, still there are 2 files that I can not remove also I don't know what are they for. Or guide me if there's anything wrong.

**Comment by wamikabro** [comment]
Okay I've removed all of them now. Have a look.

**Review by DenverCoder1 — APPROVED** [review]
Looks great! Thanks for the contribution :tada:

**Pull request merged**
