### PR TITLE
Do not add advanced prop on submit

### LINKED ISSUE #432: Every time form is submitted using enter new advanced property with red color is added
**Describe the bug**`

**To Reproduce**
1. Go to https://streak-stats.demolab.com/demo/
2. Click on Username input and type some text
3. Press enter
4. Observe some advanced property is added implicitly

Every time you press enter (i.e. submit form) the next advanced property is added with the same default colour.

**Expected behavior**
Advanced prop is not added. It should only be added explicitly, when user adds it manually.

**Screenshots**

https://user-images.githubusercontent.com/60817786/215264571-7f5ab39e-c8c1-47df-8da8-a6c2169d7930.mp4

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: v109

**Additional context**
Overall, implicit adding of advanced properties with the same value (in our case - colour) make the final result not readable.

### PR DESCRIPTION
**Pull request by timagixe**
## Description
* maps option colors with default ones
* does not set advanced prop on submit

Fixes #432 

### Type of change

- [x] Bug fix (added a non-breaking change which fixes an issue)
- [ ] New feature (added a non-breaking change which adds functionality)
- [ ] Updated documentation (updated the readme, templates, or other repo files)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- [x] Tested locally with a valid username
- [x] Tested locally with an invalid username
- [x] Ran tests with `composer test`
- [ ] Added or updated test cases to test new features

## Checklist:

- [x] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [x] The code is properly formatted and is consistent with the existing code style
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots
N/A

### CODE REVIEW

**Comment by DenverCoder1** [comment]
In my opinion, it looks better without the default option and the red color helps it stand out so it's easier to tell which attribute was added.

I think a simpler solution to the issue would be to just add the `type="button"` attribute to all the buttons to make them not treated as submit on Enter.

**Comment by timagixe** [comment]
I hope I got your right, I have tried the following and it didn't work:
```diff
- <input class="btn" type="submit" value="Open Permalink">
+ <input class="btn" type="button" value="Open Permalink">
```

With the change above, pressing `Enter` when working with form still adds advanced properties.

I have tried following two changes and they worked:
1. add event listener to form to prevent default behaviour when Enter is pressed
```diff
diff --git a/src/demo/js/script.js b/src/demo/js/script.js

 document.addEventListener("click", () => preview.update(), false);
+document.querySelector("form").addEventListener("keydown", (event) => {
+  if (event.key === 'Enter') event.preventDefault();
+});
```
2. add onkeydown handler to form element
```diff
diff --git a/src/demo/index.php b/src/demo/index.php

             <h2>Properties</h2>
-            <form class="parameters">
+            <form class="parameters" onkeydown="return event.key != 'Enter';">
                 <label for="user">Username<span title="required">*</span></label>
```

@DenverCoder1 please let me know what you think.

**Comment by DenverCoder1** [comment]
The reason it adds a property is because Enter triggers a form submit so it finds the first button that does not have the `type="button"` attribute or an input that has `type="submit"`. In this case, the Add Property button is the first button in the form so it is used as the "submit" action since it does not have `type="button"`.

Since it is not meant to submit the form, the add property button and remove property buttons should have `type="button"`. The copy button doesn't really need it since it's not inside a form, but it can't hurt to have the attribute just to signify that it is not a submit action. The Open Permalink button *could* be a submit action, but I don't know if it's really necessary to have it submit, so I think it's fine either way.

Prevent add property buttons from submitting:
```diff
--- a/src/demo/index.php
+++ b/src/demo/index.php

-                        <button class="plus btn" onclick="return preview.addProperty();">+</button>
+                        <button type="button" class="plus btn" onclick="return preview.addProperty();">+</button>
```
Prevent remove property buttons from submitting:
```diff
--- a/src/demo/js/script.js
+++ b/src/demo/js/script.js

       minus.innerText = "−";
+      minus.setAttribute("type", "button");
       minus.setAttribute("data-property", propertyName);
```
**Not required** -- Prevent "open permalink" from submitting and signify semantically that copy is not a submit:
```diff
--- a/src/demo/index.php
+++ b/src/demo/index.php

-                <input class="btn" type="submit" value="Open Permalink">
+                <input class="btn" type="button" value="Open Permalink">

-                <button class="copy-button btn tooltip" onclick="clipboard.copy(this);" onmouseout="tooltip.reset(this);" disabled>
+                <button type="button" class="copy-button btn tooltip" onclick="clipboard.copy(this);" onmouseout="tooltip.reset(this);" disabled>
```

Let me know if you think this makes sense. I've tested it and it works for me.

**Comment by timagixe** [comment]
@DenverCoder1 thank you for the detailed feedback! 🚀 I appreciate that.

I skipped adding `type` to:
1. copy button - since it is not associated with any form
2. permalink button - since it will prevent it from opening the page with all the props passed in URL

Let me know what you think.

**Review by DenverCoder1 — APPROVED** [review]
Thanks for your continued contributions, looks great :tada:

**Pull request merged**
