### PR TITLE
feat: Added Bangla Translations

### PR DESCRIPTION
**Pull request by das-amit**
## Description

This PR will introduce the required translation in _Bengali_

Fixes #236 

### Type of change

- [ ] Bug fix (added a non-breaking change which fixes an issue)
- [x] New feature (added a non-breaking change which adds functionality)
- [ ] Updated documentation (updated the readme, templates, or other repo files)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- [x] Tested locally with a valid username
- [x] Tested locally with an invalid username
- [x] Ran tests with `composer test`
- [ ] Added or updated test cases to test new features

## Checklist:

- [x] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [x] The code is properly formatted and is consistent with the existing code style
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by DenverCoder1** [comment]
Looks great! :+1: 

Could you edit the file in your branch to move `bn` above `da` so it will be in alphabetical order?

image

Also here is a preview with the locale if you can verify it looks correct:

[Preview](https://user-images.githubusercontent.com/20955511/198084392-74717a80-cc6e-4a3c-b35a-3ee3b5270502.png)

**Comment by Shelby-kun** [comment]
@DenverCoder1 looks fine, it would be better if the font is bigger, else looks okey.

**Comment by das-amit** [comment]
@DenverCoder1 looks fine. It would be better if the font was bigger, else looks fine.

**Review by DenverCoder1 — APPROVED** [review]
Looks great! Thanks for the contribution :tada:

As far as the font size, currently it is the same size for all locales. Possibly in a later PR the font scale can be made customizable per locale.

**Pull request merged**
