### PR TITLE
Change the jscolor format to HEX instead of HEXA

### LINKED ISSUE #145: Color picker adds `FF` when colors are typed into the color picker
**Describe the bug**
Color picker adds `FF` (representing full opacity) to 6-digit colors that are pasted from the clipboard or colors that were edited by typing digits.

**To Reproduce**
1. Go to the demo site
2. Click on advanced options
3. Add an option
4. Click the color picker
5. Paste a 6-digit color (eg. `#F7DF1E`) in the box or change a digit by overwriting the character
6. Notice that `FF` gets added to the end when this should only appear for partially transparent colors.

**Expected behavior**
The `FF` should not appear since the color is meant to be fully opaque.

**Screenshots**

Peek 2021-10-03 09-44

**Desktop (please complete the following information):**
- OS: Arch Linux
- Browser Brave
- Version 1.30.86 Chromium: 94.0.4606.61 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by Rocksheep**
## Description

I changed a jscolor configuration where the format was set as HEXA instead of HEX.

Fixes #145 

### Type of change

- [x] Bug fix (added a non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] Tested locally with a valid username
- [ ] Tested locally with an invalid username
- [ ] Ran tests with `composer test`
- [ ] Added or updated test cases to test new features

## Checklist:

- [x] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [x] The code is properly formatted and is consistent with the existing code style
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by DenverCoder1** [comment]
I want the site to still support hexa colors, just that when you input a hex color, it should display as hex to look cleaner. It already hides it on input (#137), but not if you use keyboard input.

**Comment by Rocksheep** [comment]
Ah alright, so you just always want it to be removed when it's FF?

**Comment by DenverCoder1** [comment]
Yeah, if you click away from the input box when it is 9 characters (# and 8 hex digits) and ends with FF, it should change it to just the first 7 characters (# and 6 hex digits) without the FF.

**Comment by Rocksheep** [comment]
I have added an onChange method on the jscolor configuration that uses the same function as the onInput function. This fixed it for me.

**Comment by DenverCoder1** [comment]
That looks good. :+1: I'm thinking maybe we could just use `onChange` *instead of* `onInput`. That way the user will still be able to type normally in the field (onInput seems to prevent that).

**Comment by Rocksheep** [comment]
Yeah I could do that, but then you get this while using the colorpicker. So it's your call!

https://user-images.githubusercontent.com/1311371/135754910-d4259163-30c9-4e0c-93ad-5063e0dbb263.mov

**Comment by DenverCoder1** [comment]
Yeah, it's a tough call. I think it's fine as is then.

**Review by DenverCoder1 — APPROVED** [review]

**Comment by DenverCoder1** [comment]
Thanks again for your contributions!

**Pull request merged**
