### PR TITLE
feat: Added Border Radius parameter

### PR DESCRIPTION
**Pull request by nishith-p-shetty**
## Description
Added Border Radius, added the same on demo site, updated readme

* added border radius for main
* added border radius for error
* added the same in demo site
* updated the css for demo site
* updated readme, adding border_radius in options

Fixes # 0

### Type of change

- [x] New feature (added a non-breaking change which adds functionality)
- [x] Updated documentation (updated the readme, templates, or other repo files)

## How Has This Been Tested?

- [x] Tested locally with a valid username
- [x] Tested locally with an invalid username
- [x] Ran tests with `composer test`
- [x] Added or updated test cases to test new features

## Checklist:

- [x] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [x] The code is properly formatted and is consistent with the existing code style
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots

You can check out border radius here >>>> https://nps-github-readme-streak-stats.herokuapp.com/?user=DenverCoder1&theme=blue-green&hide_border=false&border=FF0000&border_radius=200

Demo site >>> https://nps-github-readme-streak-stats.herokuapp.com/demo

### CODE REVIEW

**Comment by nishith-p-shetty** [comment]
You can check out border radius here >>>> https://nps-github-readme-streak-stats.herokuapp.com/?user=DenverCoder1&theme=blue-green&hide_border=false&border=FF0000&border_radius=200

Demo site >>> https://nps-github-readme-streak-stats.herokuapp.com/demo

**Comment by DenverCoder1** [comment]
The JavaScript file still needs to have the default border radius so that the preview doesn't include the border_radius when it's set to the default, and also the `value` attribute should be set to 4.5 so it doesn't display it as empty when visiting the page and not typing it.

As far as the implementation, it looks good now. 👍 

Just some formatting required and updating the tests. I can help with this if you'd like.

Also, you don't need to close and reopen pull requests, if you make changes on the branch the pull request is on, it will update the pull request. It's also recommended for the future to create a new branch for each pull request instead of using `main` to make it easier to keep it separate from other features.

**Comment by nishith-p-shetty** [comment]
what shud be done now...??

**Comment by DenverCoder1** [comment]
In the demo site it currently shows `border_radius=` when nothing is typed in making so it defaults to sharp corners, this should be fixed using `value="4.5"` so it defaults to having the default value

Screenshot_20220911-014448

Additionally, when the value is set to the default, it displays in the markdown even though it doesn't need to when it's the default. There is a mapping of default values in script js that hide values like this

Screenshot_20220911-014515

**Comment by nishith-p-shetty** [comment]
try now
fixed it using html  value="4.5"

**Comment by nishith-p-shetty** [comment]
All Ok....?

**Comment by DenverCoder1** [comment]
A default should be added in script.js so it doesn't show `border_radius=4.5` in the URL when it's the default

```diff
  defaults: {
    theme: "default",
    hide_border: "false",
    date_format: "",
    locale: "en",
+    border_radius: "4.5",
  },
```

**Comment by nishith-p-shetty** [comment]
Done

**Comment by DenverCoder1** [comment]
Looks good, just the formatting and the updating the tests now.

If you want me to handle that, feel free to ask.

**Comment by nishith-p-shetty** [comment]
Yes, U continue with it.

**Comment by nishith-p-shetty** [comment]
Will u Merge..??

**Comment by DenverCoder1** [comment]
Looks great.

There seems to be a small issue with the background color not showing up properly in PNG mode.

Actual: https://github-readm-main-e6k7rspihebb.herokuapp.com/demo/preview.php?user=&theme=gruvbox&type=png

Expected: https://streak-stats.demolab.com/demo/preview.php?user=&theme=gruvbox&type=png

I will look into it and it will be merged when that is resolved.

**Review by DenverCoder1 — APPROVED** [review]
Thanks again for the contribution :tada:

**Pull request merged**
