### PR TITLE
feat: Add Arabic translation for Excluding

### PR DESCRIPTION
**Pull request by FajarKim**
## Description

Add Arabic, Japanese, Polski, Svenska, and Kiswahili translations for Excluding

### Type of change

- [ ] Bug fix (added a non-breaking change which fixes an issue)
- [x] New feature (added a non-breaking change which adds functionality)
- [ ] Updated documentation (updated the readme, templates, or other repo files)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- [x] Tested locally with a valid username
- [x] Tested locally with an invalid username
- [x] Ran tests with `composer test`
- [x] Added or updated test cases to test new features

## Checklist:

- [x] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [x] The code is properly formatted and is consistent with the existing code style
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by DenverCoder1** [comment]
Looks good to me. Do you speak all of these languages?

**Comment by FajarKim** [comment]
> Looks good to me. Do you speak all of these languages?

Hmmm... I understand a little Arabic

**Comment by FajarKim** [comment]
Maybe you can just add Arabic

**Comment by DenverCoder1** [comment]
Thanks, while chatgpt seems to say these are all fine, I think it's better if we leave it up to native speakers to decide on how things should be translated.

I'll merge Arabic, but leave the others open to other contributors if that's fine with you.

**Comment by FajarKim** [comment]
> Thanks, while chatgpt seems to say these are all fine, I think it's better if we leave it up to native speakers to decide on how things should be translated.
> 
> I'll merge Arabic, but leave the others open to other contributors if that's fine with you.

Yes, of course. I don't mind

**Pull request merged**
