### PR TITLE
feat: Add sea-dark theme

### PR DESCRIPTION
**Pull request by AndreyKozhev**
## Description

Added new sea-dark theme.

### Type of change

- [x] Updated documentation (updated the readme, templates, or other repo files)

## How Has This Been Tested?

- [ ] Tested locally with a valid username
- [ ] Tested locally with an invalid username
- [ ] Ran tests with `composer test`
- [ ] Added or updated test cases to test new features

## Checklist:

- [x] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [x] The code is properly formatted and is consistent with the existing code style
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots

image

### CODE REVIEW

**Comment by DenverCoder1** [comment]
I kind of feel the white part seems out of place and would maybe be better with a dark color such as a dark blue or black.

Maybe something like `#00546F` would look good for the stroke?

image

Again, up to you. Let me know what you think.

**Comment by AndreyKozhev** [comment]
Okay.

**Comment by AndreyKozhev** [comment]
Ready.

**Comment by AndreyKozhev** [comment]
I don't know why, but after I updated the branch to `DenverCoder1/github-readme-streak-stats:main`, the Prettier task failed in both pull requests.

**Review by DenverCoder1 — APPROVED** [review]

**Comment by DenverCoder1** [comment]
Thanks!

**Pull request merged**
