### PR TITLE
fix: Responsiveness made to Tamil translation

### LINKED ISSUE #333: Local translate to tamil
image

1. I would like to contribute to translating the language to Tamil for users from Tamil Nadu

### PR DESCRIPTION
**Pull request by pravee42**
## Description

Fixes #333

### Type of change

- [x] Bug fix (added a non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by DenverCoder1** [comment]
I don't think the newline in longest streak is helping since it makes the second line longer

image

**Review by pravee42 — COMMENTED** [review]
Can you check now because i have updated this thing without the meaning change

**Review by DenverCoder1 — APPROVED** [review]
Looks good :+1: Hopefully this will make it look good for you as well.

image

**Comment by pravee42** [comment]
> Looks good 👍 Hopefully this will make it look good for you as well.
> 
> image

Yeah sure

**Pull request merged**
