### PR TITLE
feat: Added Marathi and corrected Hindi translation

### PR DESCRIPTION
**Pull request by SAD0XER**
## - Correct some Hindi Translations.
  - **correct 2 translation lines in Hindi.**

### CODE REVIEW

**Review by DenverCoder1 — APPROVED** [review]
Looks great! Thanks for the contribution :tada:

**Comment by SAD0XER** [comment]
###### Thanks @DenverCoder1 😃
###### Actually this was my first pull request and completely beginner to open source.

**Comment by DenverCoder1** [comment]
Awesome, keep it up! :tada: 

I'm glad my project was able to help you get started. :smile:

**Comment by SAD0XER** [comment]
Yes! It helps me to stat. 😄

**Pull request merged**
