### PR TITLE
feat: Updated Danish translations

### PR DESCRIPTION
**Pull request by JohnnyJTH**
## Description

I have finished the danish language support.

### Type of change

- [x] New feature (added a non-breaking change which adds functionality)

## Checklist:

- [x] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [x] The code is properly formatted and is consistent with the existing code style
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by DenverCoder1 — APPROVED** [review]
Awesome, thanks for contributing 👍

**Comment by DenverCoder1** [comment]
@JohnnyJTH It appears to me like this was closed before the merge. Are there any issues that need to be resolved?

> Screenshot_20230130-020810

**Comment by JohnnyJTH** [comment]
Oopsie, was I too quick? I am not that experienced with github :)

**Comment by JohnnyJTH** [comment]
It still worked right?

**Comment by DenverCoder1** [comment]
Yeah, it looks like it still worked.

I was just wondering if you had changed your mind about it or something. Just so you know, PRs can always be updated by pushing to the branch and can't easily be merged after the branch is deleted. In this case, it seems like it was merged right before the branch was deleted.

**Comment by JohnnyJTH** [comment]
Perfect, yeah no I didn't want to make any changes, just saw the accepted message and closed it. Didn't notice it wasn't merged yet :)

**Pull request closed without merging**
